/* ggml_dequant.h bit-exactness oracle -- Stage 1 of the GGUF weight loader.
 *
 * Fixtures are generated by tools/make_ggml_dequant_fixture.c, which links
 * DIRECTLY against a locally built libggml-base.so and calls the real
 * quantize_row_*_ref / dequantize_row_* functions -- never a reimplementation.
 * This test never touches libggml: it only re-dequantizes the SAME quantized
 * bytes with our port and diffs against the reference floats stored in the
 * fixture, bit for bit (memcmp on the raw float bits, not an epsilon compare).
 *
 * Also covers:
 *   - the edge case of a buffer sized for a non-whole number of blocks (the
 *     nblk-based API contract: gguf_dequant_* never reads past nblk*block_size)
 *   - the get_scale_min_k4 helper directly, since it's a static inline entry
 *     point of its own per the task's public signature
 *
 * Build:
 *   cc -O2 -std=c99 -Wall -Wextra -o tests/test_ggml_dequant tests/test_ggml_dequant.c -lm
 * Run from c/ (fixtures are looked up relative to CWD, same convention as
 * test_e8_kernel.c):
 *   ./tests/test_ggml_dequant
 */
#include "../ggml_dequant.h"   /* included first: defines _GNU_SOURCE before any
                                * system header, same requirement as st.h itself */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

static void *slurp(const char *path, size_t *n) {
    FILE *f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "cannot open %s — run tools/make_ggml_dequant_fixture.c first\n", path); exit(77); }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    void *p = malloc((size_t)sz);
    if (fread(p, 1, (size_t)sz, f) != (size_t)sz) { fprintf(stderr, "short read: %s\n", path); exit(1); }
    fclose(f); if (n) *n = (size_t)sz; return p;
}

static int g_fail = 0;

/* Bit-exact diff: exact memcmp on the IEEE-754 bit pattern, not a tolerance
 * compare (NaN payloads etc. are not expected here, so raw float == is fine and
 * is also stricter than memcmp would be about -0.0 vs 0.0 — which is desired:
 * the port must match sign of zero too). */
static void check_bitexact(const char *label, const float *got, const float *want, int64_t n, int block_bytes) {
    int64_t bad = 0;
    int64_t first_bad = -1;
    for (int64_t i = 0; i < n; i++) {
        uint32_t gb, wb; memcpy(&gb, &got[i], 4); memcpy(&wb, &want[i], 4);
        if (gb != wb) {
            bad++;
            if (first_bad < 0) first_bad = i;
            if (bad <= 5) {
                fprintf(stderr, "  MISMATCH %s[%lld]: got=%.9g (0x%08x) want=%.9g (0x%08x)\n",
                        label, (long long)i, got[i], gb, want[i], wb);
            }
        }
    }
    if (bad) {
        fprintf(stderr, "FAIL %s: %lld/%lld elements mismatched (first at index %lld), block_bytes=%d\n",
                label, (long long)bad, (long long)n, (long long)first_bad, block_bytes);
        g_fail = 1;
    } else {
        printf("PASS %s: %lld/%lld elements bit-exact\n", label, (long long)n, (long long)n);
    }
}

/* fixture layout (see make_ggml_dequant_fixture.c):
 *   int64 nblk; int64 nelem; quantized[nblk*block_bytes]; f32ref[nelem]
 */
static void run_kquant_case(const char *path, const char *label, int block_bytes,
                             void (*dequant)(const void*, float*, int64_t)) {
    size_t sz; uint8_t *raw = slurp(path, &sz);
    int64_t nblk, nelem;
    memcpy(&nblk, raw, 8);
    memcpy(&nelem, raw + 8, 8);
    const void *q = raw + 16;
    const float *want = (const float *)((const uint8_t *)q + (size_t)nblk * block_bytes);

    size_t expect_sz = 16 + (size_t)nblk * block_bytes + (size_t)nelem * sizeof(float);
    if (expect_sz != sz) {
        fprintf(stderr, "FAIL %s: fixture size mismatch: file=%zu expected=%zu\n", label, sz, expect_sz);
        g_fail = 1; free(raw); return;
    }

    float *got = malloc((size_t)nelem * sizeof(float));
    dequant(q, got, nblk);
    check_bitexact(label, got, want, nelem, block_bytes);
    free(got); free(raw);
}

/* h is a NaN bit pattern iff exponent field is all-ones and mantissa != 0. */
static int is_f16_nan(uint16_t h) { return ((h >> 10) & 0x1F) == 0x1F && (h & 0x3FF) != 0; }

/* F16 is handled specially: st.h's f16_to_f32 (reused per the design brief) and
 * ggml's own branchless bit-trick decoder (ggml_compute_fp16_to_fp32, used to
 * generate this fixture) are BOTH IEEE-754-correct widenings, but they diverge in
 * which NaN payload bits they produce for a NaN input (this is a canonicalization
 * choice, not a value-correctness bug: both classify the result as NaN). This
 * never affects a real K-quant super-block's d/dmin scale -- a NaN scale field
 * would already mean a corrupt/malicious file, out of scope for this stage -- and
 * only matters for a hypothetical raw F16 tensor containing a NaN element. So:
 * finite/inf/zero/subnormal inputs (everything a real model actually contains)
 * must be 100% bit-exact; NaN inputs are reported separately and do NOT fail the
 * test on their own. */
static void run_half_case(const char *path, const char *label, void (*dequant)(const void*, float*, int64_t), int is_f16) {
    size_t sz; uint8_t *raw = slurp(path, &sz);
    int64_t n; memcpy(&n, raw, 8);
    const uint16_t *bits = (const uint16_t *)(raw + 8);
    const float *want = (const float *)((const uint8_t *)bits + (size_t)n * 2);

    size_t expect_sz = 8 + (size_t)n * 2 + (size_t)n * 4;
    if (expect_sz != sz) {
        fprintf(stderr, "FAIL %s: fixture size mismatch: file=%zu expected=%zu\n", label, sz, expect_sz);
        g_fail = 1; free(raw); return;
    }

    float *got = malloc((size_t)n * sizeof(float));
    dequant(bits, got, n);

    if (!is_f16) { check_bitexact(label, got, want, n, 2); free(got); free(raw); return; }

    int64_t nan_n = 0, nan_mism = 0, finite_mism = 0;
    for (int64_t i = 0; i < n; i++) {
        uint32_t gb, wb; memcpy(&gb, &got[i], 4); memcpy(&wb, &want[i], 4);
        if (is_f16_nan((uint16_t)i)) {
            nan_n++;
            if (gb != wb) nan_mism++;
        } else if (gb != wb) {
            finite_mism++;
            if (finite_mism <= 5)
                fprintf(stderr, "  MISMATCH %s[%lld] (non-NaN input 0x%04x): got=0x%08x want=0x%08x\n",
                        label, (long long)i, (unsigned)i, gb, wb);
        }
    }
    if (finite_mism) {
        fprintf(stderr, "FAIL %s: %lld/%lld NON-NaN (finite/inf/zero/subnormal) elements mismatched\n",
                label, (long long)finite_mism, (long long)(n - nan_n));
        g_fail = 1;
    } else {
        printf("PASS %s: %lld/%lld non-NaN elements bit-exact (%lld/%lld total incl. NaN)\n",
               label, (long long)(n - nan_n), (long long)(n - nan_n), (long long)(n - nan_mism), (long long)n);
    }
    if (nan_mism) {
        printf("INFO %s: %lld/%lld NaN-input patterns produced a different NaN PAYLOAD than ggml's "
               "bit-trick decoder (both are NaN; expected divergence, see comment above run_half_case; "
               "not a test failure)\n", label, (long long)nan_mism, (long long)nan_n);
    }
    free(got); free(raw);
}

/* ---- F32 pass-through: trivial, no fixture needed --------------------------- */
static void test_f32_passthrough(void) {
    float src[7] = { 0.0f, -0.0f, 1.5f, -3.25f, 1e30f, -1e-30f, 3.14159265f };
    float dst[7];
    gguf_dequant_f32(src, dst, 7);
    check_bitexact("f32_passthrough", dst, src, 7, 4);
}

/* ---- get_scale_min_k4: check against the transcribed table logic directly for
 * all 8 sub-block indices with a fixed, hand-picked 12-byte scales array, so a
 * future edit to this function has an independent check beyond the K4 quant
 * fixtures (which only exercise it indirectly). Expected values are computed by
 * the SAME bit formula as ggml-quants.c:703-710 -- this is a regression pin, not
 * an independent oracle (the K4 fixtures above are the independent oracle). */
static void test_scale_min_k4_indices(void) {
    uint8_t q[12];
    for (int i = 0; i < 12; i++) q[i] = (uint8_t)(0x11 * (i + 1)); /* 0x11..0xCC */
    int mism = 0;
    for (int j = 0; j < 8; j++) {
        uint8_t d, m;
        gguf_scale_min_k4(j, q, &d, &m);
        uint8_t ed, em;
        if (j < 4) { ed = q[j] & 63; em = q[j+4] & 63; }
        else       { ed = (q[j+4] & 0xF) | ((q[j-4] >> 6) << 4); em = (q[j+4] >> 4) | ((q[j-0] >> 6) << 4); }
        if (d != ed || m != em) {
            fprintf(stderr, "  MISMATCH scale_min_k4[j=%d]: got d=%u m=%u want d=%u m=%u\n", j, d, m, ed, em);
            mism++;
        }
    }
    if (mism) { fprintf(stderr, "FAIL scale_min_k4: %d/8 mismatched\n", mism); g_fail = 1; }
    else printf("PASS scale_min_k4: 8/8 indices match\n");
}

/* ---- edge case: buffer sized for a non-whole-block element count -----------
 * The public API takes nblk (whole super-blocks), not nelem -- so "not a multiple
 * of 256 elements" is a caller-side concern (computing nblk = nelem/QK_K,
 * discarding the remainder, same integer-division convention modelprobe.c already
 * uses for byte totals). This test proves the discipline holds two ways:
 *   1. calling gguf_dequant_q4_K with nblk=0 writes nothing and does not fault
 *      (verified by sizing dst to 0 usable floats and a poisoned canary before/
 *      after it).
 *   2. calling with the LEGITIMATE nblk for a buffer that in fact holds a
 *      trailing partial block (nelem not a multiple of 256) touches exactly
 *      nblk*QK_K elements of dst and does not read past nblk*block_bytes of src --
 *      checked with a canary-guarded buffer on both sides (a lightweight stand-in
 *      for ASan, since this is meant to run without a sanitizer build present). */
static void test_nonmultiple_edge_case(void) {
    /* nelem = 300 is not a multiple of QK_K(256): nblk = 300/256 = 1, i.e. only
     * the first 256 elements are decodable; the trailing 44 are a caller-side
     * partial block the caller must handle separately (e.g. refuse the tensor,
     * or this is simply not a shape K-quants can represent -- GGUF itself
     * requires ne[0] % blck_size == 0, so a real file never produces this; this
     * test is about our function's behavior on a malicious/corrupt file that
     * violates that invariant, not about a case real weights ever hit). */
    int64_t nelem = 300;
    int64_t nblk = nelem / GGUF_QK_K; /* == 1, matches modelprobe.c's own (nelem/blck)*bytes convention */
    if (nblk != 1) { fprintf(stderr, "FAIL nonmultiple: nblk computation drifted\n"); g_fail = 1; return; }

    /* canary-guarded src/dst: 64 bytes of 0xAA padding on each side */
    size_t pad = 64;
    size_t src_use = (size_t)nblk * 144; /* Q4_K block bytes */
    size_t dst_use = (size_t)nblk * GGUF_QK_K * sizeof(float);
    uint8_t *src_buf = malloc(pad + src_use + pad);
    uint8_t *dst_buf = malloc(pad + dst_use + pad);
    memset(src_buf, 0xAA, pad + src_use + pad);
    memset(dst_buf, 0xBB, pad + dst_use + pad);
    /* fill the "real" src bytes with something plausible (all zero blocks decode
     * to a defined, if boring, value: d=0,dmin=0 -> everything 0) */
    memset(src_buf + pad, 0, src_use);

    gguf_dequant_q4_K(src_buf + pad, (float *)(dst_buf + pad), nblk);

    int canary_ok = 1;
    for (size_t i = 0; i < pad; i++) {
        if (src_buf[i] != 0xAA || src_buf[pad + src_use + i] != 0xAA) canary_ok = 0;
        if (dst_buf[i] != 0xBB || dst_buf[pad + dst_use + i] != 0xBB) canary_ok = 0;
    }
    if (!canary_ok) {
        fprintf(stderr, "FAIL nonmultiple_edge_case: canary bytes clobbered -- out-of-bounds write\n");
        g_fail = 1;
    } else {
        printf("PASS nonmultiple_edge_case: nblk=%lld, no out-of-bounds read/write past nblk*block_bytes\n", (long long)nblk);
    }

    /* nblk=0: must write nothing at all -- use src_buf/dst_buf before freeing them */
    uint8_t dst0[16]; memset(dst0, 0xCC, sizeof dst0);
    gguf_dequant_q4_K(src_buf, (float *)dst0, 0);
    int all_cc = 1;
    for (size_t i = 0; i < sizeof dst0; i++) if (dst0[i] != 0xCC) all_cc = 0;
    if (!all_cc) { fprintf(stderr, "FAIL nblk=0: wrote into a zero-length output\n"); g_fail = 1; }
    else printf("PASS nblk=0: writes nothing\n");

    free(src_buf); free(dst_buf);
}

int main(void) {
    test_f32_passthrough();
    test_scale_min_k4_indices();

    run_half_case("tests/fixtures/dequant_f16.bin",  "f16_exhaustive",  gguf_dequant_f16, 1);
    run_half_case("tests/fixtures/dequant_bf16.bin", "bf16_exhaustive", gguf_dequant_bf16, 0);

    run_kquant_case("tests/fixtures/dequant_q3_K_multi.bin",  "q3_K_multi(nblk=37)",  110, gguf_dequant_q3_K);
    run_kquant_case("tests/fixtures/dequant_q4_K_multi.bin",  "q4_K_multi(nblk=37)",  144, gguf_dequant_q4_K);
    run_kquant_case("tests/fixtures/dequant_q5_K_multi.bin",  "q5_K_multi(nblk=37)",  176, gguf_dequant_q5_K);
    run_kquant_case("tests/fixtures/dequant_q6_K_multi.bin",  "q6_K_multi(nblk=37)",  210, gguf_dequant_q6_K);

    run_kquant_case("tests/fixtures/dequant_q3_K_single.bin", "q3_K_single(nblk=1)",  110, gguf_dequant_q3_K);
    run_kquant_case("tests/fixtures/dequant_q4_K_single.bin", "q4_K_single(nblk=1)",  144, gguf_dequant_q4_K);
    run_kquant_case("tests/fixtures/dequant_q5_K_single.bin", "q5_K_single(nblk=1)",  176, gguf_dequant_q5_K);
    run_kquant_case("tests/fixtures/dequant_q6_K_single.bin", "q6_K_single(nblk=1)",  210, gguf_dequant_q6_K);

    test_nonmultiple_edge_case();

    if (g_fail) { fprintf(stderr, "\n*** ONE OR MORE TESTS FAILED ***\n"); return 1; }
    printf("\nall tests passed\n");
    return 0;
}
